
package GUI_Assignment4;

import ClassHiearchy_Assignment3.Classroom;
import ClassHiearchy_Assignment3.DataContainer;
import ClassHiearchy_Assignment3.OfferedClass;
import Exceptions_Assignment7.NoDataException;
import Validators.validateFields;
import javax.swing.JOptionPane;


/**
 *
 * @author Bryan
 */
public class AddClassWindow extends javax.swing.JFrame {
    private DataContainer container;
    /**
     * Creates new form AddClassWindow
     */
    public AddClassWindow() {
        initComponents();
    }
    
    public AddClassWindow(DataContainer container){
        initComponents();
        this.container = container;
        labButton.setSelected(true);
        typeButtons.add(labButton);
        typeButtons.add(classroomButton);
        typeButtons.add(hallButton);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        typeButtons = new javax.swing.ButtonGroup();
        classNameLabel = new javax.swing.JLabel();
        roomNumberLabel = new javax.swing.JLabel();
        classIdLabel = new javax.swing.JLabel();
        classNameInput = new javax.swing.JTextField();
        roomNumberInput = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        labButton = new javax.swing.JRadioButton();
        classroomButton = new javax.swing.JRadioButton();
        hallButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        classNameLabel.setText("Class Name");

        roomNumberLabel.setText("Room Number");

        classIdLabel.setText("Class ID");

        classNameInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classNameInputActionPerformed(evt);
            }
        });

        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel/Clear");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        labButton.setText("lab");

        classroomButton.setText("classroom");

        hallButton.setText("lecture hall");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(roomNumberLabel)
                            .addComponent(classNameLabel)
                            .addComponent(classIdLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(classNameInput, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(roomNumberInput)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveButton)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)
                        .addGap(18, 18, 18)
                        .addComponent(exitButton))
                    .addComponent(labButton)
                    .addComponent(classroomButton)
                    .addComponent(hallButton))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cancelButton, exitButton, saveButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classNameLabel)
                    .addComponent(classNameInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roomNumberLabel)
                    .addComponent(roomNumberInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(classIdLabel)
                .addGap(18, 18, 18)
                .addComponent(labButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(classroomButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hallButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton)
                    .addComponent(saveButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void classNameInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classNameInputActionPerformed
                // TODO add your handling code here:
        
    }//GEN-LAST:event_classNameInputActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:

        
        Classroom classRoom = new Classroom();
        OfferedClass offered = new OfferedClass();
        
        //Check room Name and room number fields
        try{
            validateFields.validateText(roomNumberInput.getText());
        }
        catch(NoDataException e){
            JOptionPane.showMessageDialog(null, "Pleas enter a room number.");
            return;
        }
        
        try{
            validateFields.validateText(classNameInput.getText());
        }
        catch(NoDataException e)
        {
            JOptionPane.showMessageDialog(null, "Please enter a class name.");
            return;
        }
        // if all fields properly filled, set and save data
        classRoom.setClassroomNumber(roomNumberInput.getText());
        classRoom.setClassName(classNameInput.getText());
        
        if(labButton.isSelected())
            classRoom.setClassroomStatus('l');
        else if (classroomButton.isSelected())
            classRoom.setClassroomStatus('c');
        else if (hallButton.isSelected())
            classRoom.setClassroomStatus('h');
        
        offered.setClassroom(classRoom);
        offered.setClassName(classNameInput.getText());
        
        
        container.getClassrooms().add(classRoom);
        container.getOffered().add(offered);
        
                
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        
        classNameInput.setText("");
        roomNumberInput.setText("");
        labButton.isSelected();
        
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddClassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddClassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddClassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddClassWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddClassWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel classIdLabel;
    private javax.swing.JTextField classNameInput;
    private javax.swing.JLabel classNameLabel;
    private javax.swing.JRadioButton classroomButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JRadioButton hallButton;
    private javax.swing.JRadioButton labButton;
    private javax.swing.JTextField roomNumberInput;
    private javax.swing.JLabel roomNumberLabel;
    private javax.swing.JButton saveButton;
    private javax.swing.ButtonGroup typeButtons;
    // End of variables declaration//GEN-END:variables
}
