/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package GUI_Assignment4;



import ClassHiearchy_Assignment3.DataContainer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;

/**
 *
 * @author Bryan
 */
public class MainMenu extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form MainMenu
     */

    private DataContainer container = new DataContainer();
    
    
    public MainMenu() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);  

        // deserialize saved data
        // All Student, Faculty, Classroom, and OfferedClass objects serialized
        // upon exit.
        
        
            try{
                if(container.getStudentsFile().exists())
                    container.deSerializeStudents();
                if(container.getFacultyFile().exists())
                    container.deSerializeFaculty();
                if(container.getClassroomsFile().exists())
                    container.deSerializeClassrooms();
                if(container.getOfferedFile().exists())
                    container.deSerializeOffered();
            }catch(Exception e){
                System.out.println("No saved data found.");
            }
        

        //set action listeners of page buttons = to their menu item counterparts
        addStudentWindow.addActionListener(new java.awt.event.ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentMenuItemActionPerformed(evt);
            }
        });
        viewStudentWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentMenuItemActionPerformed(evt);
            }
        });

        
        addFacultyWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyMenuItemActionPerformed(evt);
            }
        });
        

            
        viewFacultyWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFacultyMenuItemActionPerformed(evt);
            }
        });

        
        addClassWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassMenuItemActionPerformed(evt);
            }
        });
        
        viewClassWindow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewClassMenuItemActionPerformed(evt);
            }
        });
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addFacultyWindow = new javax.swing.JButton();
        viewFacultyWindow = new javax.swing.JButton();
        addClassWindow = new javax.swing.JButton();
        viewClassWindow = new javax.swing.JButton();
        addStudentWindow = new javax.swing.JButton();
        viewStudentWindow = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        studentMenuBar = new javax.swing.JMenu();
        addStudentMenuItem = new javax.swing.JMenuItem();
        viewStudentMenuItem = new javax.swing.JMenuItem();
        facultyMenuBar = new javax.swing.JMenu();
        addFacultyMenuItem = new javax.swing.JMenuItem();
        viewFacultyMenuItem = new javax.swing.JMenuItem();
        classesMenuBar = new javax.swing.JMenu();
        addClassMenuItem = new javax.swing.JMenuItem();
        viewClassMenuItem = new javax.swing.JMenuItem();
        exitMenuBar = new javax.swing.JMenu();
        exitButton = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        addFacultyWindow.setText("Add Faculty");

        viewFacultyWindow.setText("View Facutly");

        addClassWindow.setText("Add Class");

        viewClassWindow.setText("View Class");

        addStudentWindow.setText("Add Student");

        viewStudentWindow.setText("View Student");

        studentMenuBar.setText("Student");

        addStudentMenuItem.setText("Add Student");
        addStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentMenuItemActionPerformed(evt);
            }
        });
        studentMenuBar.add(addStudentMenuItem);

        viewStudentMenuItem.setText("View Students");
        viewStudentMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewStudentMenuItemActionPerformed(evt);
            }
        });
        studentMenuBar.add(viewStudentMenuItem);

        jMenuBar2.add(studentMenuBar);

        facultyMenuBar.setText("Faculty");

        addFacultyMenuItem.setText("Add Faculty");
        addFacultyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFacultyMenuItemActionPerformed(evt);
            }
        });
        facultyMenuBar.add(addFacultyMenuItem);

        viewFacultyMenuItem.setText("View Faculty");
        viewFacultyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFacultyMenuItemActionPerformed(evt);
            }
        });
        facultyMenuBar.add(viewFacultyMenuItem);

        jMenuBar2.add(facultyMenuBar);

        classesMenuBar.setText("Classes");

        addClassMenuItem.setText("Add Class");
        addClassMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addClassMenuItemActionPerformed(evt);
            }
        });
        classesMenuBar.add(addClassMenuItem);

        viewClassMenuItem.setText("View Classes");
        viewClassMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewClassMenuItemActionPerformed(evt);
            }
        });
        classesMenuBar.add(viewClassMenuItem);

        jMenuBar2.add(classesMenuBar);

        exitMenuBar.setText("Exit");
        exitMenuBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuBarActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });
        exitMenuBar.add(exitButton);

        jMenuBar2.add(exitMenuBar);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viewStudentWindow)
                        .addGap(18, 18, 18)
                        .addComponent(viewFacultyWindow)
                        .addGap(18, 18, 18)
                        .addComponent(viewClassWindow))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addStudentWindow)
                        .addGap(18, 18, 18)
                        .addComponent(addFacultyWindow)
                        .addGap(18, 18, 18)
                        .addComponent(addClassWindow)))
                .addGap(0, 127, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {addClassWindow, addFacultyWindow, addStudentWindow, viewClassWindow, viewFacultyWindow, viewStudentWindow});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addFacultyWindow)
                    .addComponent(addClassWindow)
                    .addComponent(addStudentWindow))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewFacultyWindow)
                    .addComponent(viewClassWindow)
                    .addComponent(viewStudentWindow))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void viewStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewStudentMenuItemActionPerformed
        // TODO add your handling code here:
        ViewStudentInfoWindow viewStudent = new ViewStudentInfoWindow(container);
        viewStudent.setVisible(true);    
    }//GEN-LAST:event_viewStudentMenuItemActionPerformed

    private void addStudentMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentMenuItemActionPerformed
        // TODO add your handling code here:
       
        AddStudentWindow addStudent = new AddStudentWindow(container);
        addStudent.setVisible(true);
    }//GEN-LAST:event_addStudentMenuItemActionPerformed

    private void addFacultyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFacultyMenuItemActionPerformed
        // TODO add your handling code here:
        AddFacultyWindow addFaculty;
        addFaculty = new AddFacultyWindow(container);
        addFaculty.setVisible(true);
    }//GEN-LAST:event_addFacultyMenuItemActionPerformed

    private void addClassMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addClassMenuItemActionPerformed
        // TODO add your handling code here:
        AddClassWindow addClass = new AddClassWindow(container);
        addClass.setVisible(true);
    }//GEN-LAST:event_addClassMenuItemActionPerformed

    private void viewFacultyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFacultyMenuItemActionPerformed
        // TODO add your handling code here:
        ViewFacultyWindow viewFaculty;
        viewFaculty = new ViewFacultyWindow(container);
        viewFaculty.setVisible(true);
        
    }//GEN-LAST:event_viewFacultyMenuItemActionPerformed

    private void viewClassMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewClassMenuItemActionPerformed
        // TODO add your handling code here:

        ViewClassWindow viewClass = new ViewClassWindow(container);
        viewClass.setVisible(true);
        
    }//GEN-LAST:event_viewClassMenuItemActionPerformed

    private void exitMenuBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuBarActionPerformed
        //serialize Container objects
        try{
            container.serializeStudents();
            container.serializeFaculty();
            container.serializeClassrooms();
            container.serializeOffered();
            
        }catch(FileNotFoundException e){
            System.out.println("Error serializing data files.");
        } 
       
        System.exit(0);
    }//GEN-LAST:event_exitMenuBarActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        // TODO add your handling code here:
        container.writeDataToTextFile();
        try {
            container.serializeStudents();
            container.serializeFaculty();
            container.serializeClassrooms();
            container.serializeOffered();
        } catch (FileNotFoundException ex) {
            System.out.println("File not Found");
        }

        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addClassMenuItem;
    private javax.swing.JButton addClassWindow;
    private javax.swing.JMenuItem addFacultyMenuItem;
    private javax.swing.JButton addFacultyWindow;
    private javax.swing.JMenuItem addStudentMenuItem;
    private javax.swing.JButton addStudentWindow;
    private javax.swing.JMenu classesMenuBar;
    private javax.swing.JMenuItem exitButton;
    private javax.swing.JMenu exitMenuBar;
    private javax.swing.JMenu facultyMenuBar;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenu studentMenuBar;
    private javax.swing.JMenuItem viewClassMenuItem;
    private javax.swing.JButton viewClassWindow;
    private javax.swing.JMenuItem viewFacultyMenuItem;
    private javax.swing.JButton viewFacultyWindow;
    private javax.swing.JMenuItem viewStudentMenuItem;
    private javax.swing.JButton viewStudentWindow;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent ae) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
