

package GUI_Assignment4;

import ClassHiearchy_Assignment3.DataContainer;
import ClassHiearchy_Assignment3.Student;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Bryan
 */
public class ViewStudentInfoWindow extends javax.swing.JFrame{
    
    private DataContainer container;
    private DefaultTableModel tableModel;
    private SimpleDateFormat formatter = new SimpleDateFormat("MM-dd-YY");
    
    /**
     * Creates new form ViewStudentInfoWindow
     */
    public ViewStudentInfoWindow() {
        initComponents();
    }
    
    public ViewStudentInfoWindow(DataContainer container){
        initComponents();
        this.container = container;
               //Creat the table to hold classroom data
        String [] columnNames = {"Name", "Address", "SSN",
                                "Birth Date", "Graduation Date",
                                "GPA", "Enrolled In"};
        tableModel = new DefaultTableModel(columnNames, 0);
       
        
        studentTable.setModel(tableModel); 
        //studentPane.setViewportView(studentTable);
        studentTable.setVisible(true); 
        for(Student student : container.getStudents())
        {
            Object [] students = new Object [7];
            
            students[0] = student.getName();
            students[1] = student.getAddress();
            students[2] = student.getSSN();
            students[3] = formatter.format(student.getDateOfBirth().getTime());
            students[4] = formatter.format(student.getDateOfGraduation().getTime());
            students[5] = student.calculateGPA();
            students[6] = student.getClasses().toString();

            
            tableModel.addRow(students);
        }
        final TableColumnModel columnModel = studentTable.getColumnModel();
        for (int column = 0; column < studentTable.getColumnCount(); column++) {
            int width = 50; // Min width
            for (int row = 0; row < studentTable.getRowCount(); row++) {
                TableCellRenderer renderer = studentTable.getCellRenderer(row, column);
                Component comp = studentTable.prepareRenderer(renderer, row, column);
                width = Math.max(comp.getPreferredSize().width, width);
        }
        columnModel.getColumn(column).setPreferredWidth(width);
    }
        studentTable.setColumnModel(columnModel);

        
    }
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        studentPane = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Students");

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        studentPane.setViewportView(studentTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(studentPane, javax.swing.GroupLayout.DEFAULT_SIZE, 672, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(studentPane, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewStudentInfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewStudentInfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewStudentInfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewStudentInfoWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewStudentInfoWindow().setVisible(true);
                
            }

        });
        
    }
    


    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane studentPane;
    private javax.swing.JTable studentTable;
    // End of variables declaration//GEN-END:variables
}
